version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bot_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bot-network

  db:
    container_name: postgres_db
    image: postgres:15
    environment:
      - POSTGRES_DB=bot_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  bot-network:
    driver: bridge
